# Pune House Price Prediction — Data Cleaning

## 1. Project Objective
The objective of this notebook is to inspect, clean, and validate the raw Pune property dataset before performing exploratory data analysis and developing machine learning models.

## 2. Data Cleaning Workflow
- Inspect the dataset structure and dimensions.
- Identify missing values and duplicate records.
- Examine data types and inconsistent values.
- Investigate invalid records and potential outliers.
- Apply appropriate cleaning techniques.
- Validate and save the cleaned dataset.

**Important:** The original raw dataset will remain unchanged. All cleaning operations will be performed on a separate working copy.

In [39]:
import pandas as pd
import numpy as np
import re
from pathlib import Path
from IPython.display import display

In [40]:
PROJECT_ROOT = Path(r"D:/Pune-House-Price-Prediction")

RAW_PATH = PROJECT_ROOT / "data" / "raw" / "Pune_property_data.csv"

OUTPUT_PATH = PROJECT_ROOT / "data" / "processed" / "pune_cleaned_reference.csv"

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

In [41]:
df = pd.read_csv(RAW_PATH)

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)

display(df.head())

Dataset loaded successfully!
Rows and columns: (37539, 24)

,Unnamed: 0,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,...,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
0,0,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,Indoor...","24 X 7 Security,Children's play area,Club Hous...","1,611 sq ft",2,3,3 BHK Apartment,1209 sq ft,...,2,Road View,Co-Operative Society,NaN,27000000,"₹ 16,759/ sq ft",Bhansali Prive Rio,40 feet,Ready to move,6
1,1,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","Children's play area,Sports Facility,Landscape...","1,279 sq ft",NaN,2,2 BHK Apartment,NaN,...,NaN,NaN,Freehold,NaN,7610050,"₹ 5,950/ sq ft",Goel Ganga Platino,NaN,Ready to move,NaN
2,2,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",Sports Facility,670 sq ft,NaN,1,1 BHK Apartment,NaN,...,NaN,NaN,Freehold,NaN,4100000,"₹ 6,119/ sq ft",Vilas Javdekar Yashwin,NaN,Ready to move,NaN
3,3,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,24 X 7...","Sports Facility,Landscaped Gardens",956 sq ft,NaN,2,2 BHK Apartment,615 sq ft,...,NaN,NaN,Freehold,NaN,5736000,"₹ 6,000/ sq ft",Rohan Ishan,NaN,Ready to move,NaN
4,4,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","Club House,Swimming Pool,Sports Facility,Joggi...","1,706 sq ft",1,3,3 BHK Apartment,1195 sq ft,...,2,Road View,Freehold,NaN,29002000,"₹ 17,000/ sq ft",Swojas Aavishkar,60 feet,Ready to move,9

In [42]:
print("Column names:")
print(df.columns.tolist())

print("\nData types:")
display(df.dtypes.to_frame(name="Data Type"))

print("\nDataset information:")
df.info()

Column names:
['Unnamed: 0', 'additionalrooms', 'age', 'amenitiesavailable', 'amenitiesnot', 'area', 'balconies', 'bathroom', 'bhk', 'carpetarea', 'facing', 'floor', 'locality', 'neworold', 'opensides', 'overlooking', 'ownership', 'possesiondate', 'price', 'pricepersquare', 'projectname', 'roadfaceing', 'status', 'totalfloor']

Data types:

                   Data Type
Unnamed: 0             int64
additionalrooms          str
age                      str
amenitiesavailable       str
amenitiesnot             str
area                     str
balconies                str
bathroom                 str
bhk                      str
carpetarea               str
facing                   str
floor                    str
locality                 str
neworold                 str
opensides                str
overlooking              str
ownership                str
possesiondate            str
price                    str
pricepersquare           str
projectname              str
roadfaceing              str
status                   str
totalfloor               str

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 37539 entries, 0 to 37538
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          37539 non-null  int64
 1   additionalrooms     9321 non-null   str
 2   age                 27637 non-null  str
 3   amenitiesavailable  34445 non-null  str
 4   amenitiesnot        34286 non-null  str
 5   area                37518 non-null  str
 6   balconies           21911 non-null  str
 7   bathroom            34667 non-null  str
 8   bhk                 37538 non-null  str
 9   carpetarea          8622 non-null   str
 10  facing              30919 non-null  str
 11  floor               31919 non-null  str
 12  locality            37538 non-null  str
 13  neworold            37538 non-null  str
 14  opensides           11605 non-null  str
 15  overlooking         17140 non-null  str
 16  ownership           28156 non-null  str
 17  possesiondate       4736 non-null   str
 18  price               37538 non-null  str
 19  pricepersquare      37538 non-null  str
 20  projectname         24129 non-null  str
 21  roadfaceing         6875 non-null   str
 22  status              36078 non-null  str
 23  totalfloor          24114 non-null  str
dtypes: int64(1), str(23)
memory usage: 20.3 MB

In [43]:
cleaned_df = df.copy()

print("Working copy created.")
print("Shape:", cleaned_df.shape)

Working copy created.
Shape: (37539, 24)

In [44]:
header_mask = (
    cleaned_df["neworold"].astype("string").str.strip().str.lower().eq("neworold")
    | cleaned_df["ownership"].astype("string").str.strip().str.lower().eq("ownership")
    | cleaned_df["status"].astype("string").str.strip().str.lower().eq("status")
)

print("Rows identified as repeated headers:", int(header_mask.sum()))

cleaned_df = cleaned_df.loc[~header_mask].copy()

print("Shape after removing repeated headers:", cleaned_df.shape)

Rows identified as repeated headers: 22
Shape after removing repeated headers: (27700, 24)

In [45]:
text_columns = cleaned_df.select_dtypes(
    include=["object", "string"]
).columns

for column in text_columns:
    cleaned_df[column] = cleaned_df[column].astype("string").str.strip()

print("Text columns standardized.")

Text columns standardized.

In [46]:
lowercase_columns = ["facing", "locality", "neworold"]

for column in lowercase_columns:
    cleaned_df[column] = cleaned_df[column].str.lower()

print("Selected categorical columns converted to lowercase.")

display(cleaned_df[lowercase_columns].head())

Selected categorical columns converted to lowercase.

      facing         locality neworold
0       west  deccan gymkhana      new
1  northeast          kharadi      new
2  northeast              sus      new
3  northeast          bavdhan      new
4       west  deccan gymkhana      new

In [47]:
cleaned_df["ownership"] = cleaned_df["ownership"].replace({
    "Leasehol": "leasehold",
    "leasehol": "leasehold",
    "LEASEHOL": "leasehold"
})

print(cleaned_df["ownership"].value_counts(dropna=False).head(10))

ownership
Freehold                24952
Co-Operative Society     2599
leasehold                 105
Power of Attorney          44
Name: count, dtype: int64[pyarrow]

In [48]:
cleaned_df["Area"] = pd.to_numeric(
    cleaned_df["area"]
    .astype("string")
    .str.replace(",", "", regex=False)
    .str.extract(r"(\d+(?:\.\d+)?)", expand=False),
    errors="coerce"
)

display(cleaned_df[["area", "Area"]].head(10))

          area  Area
0  1,611 sq ft  1611
1  1,279 sq ft  1279
2    670 sq ft   670
3    956 sq ft   956
4  1,706 sq ft  1706
5  1,015 sq ft  1015
6  3,725 sq ft  3725
7    450 sq ft   450
8  1,650 sq ft  1650
9    449 sq ft   449

In [49]:
age_text = cleaned_df["age"].astype("string").str.strip()

age_range_upper = pd.to_numeric(
    age_text.str.extract(r"-\s*(\d+(?:\.\d+)?)", expand=False),
    errors="coerce"
)

age_single_value = pd.to_numeric(
    age_text.str.extract(r"^\s*(\d+(?:\.\d+)?)\s*years?\s*$", expand=False),
    errors="coerce"
)

cleaned_df["Age"] = age_range_upper.fillna(age_single_value)

display(cleaned_df[["age", "Age"]].head(15))

            age   Age
0   2 - 3 years     3
1    0 - 1 year     1
2    0 - 1 year     1
3   2 - 3 years     3
4    0 - 1 year     1
5    0 - 1 year     1
6   1 - 2 years     2
7    0 - 1 year     1
8   1 - 2 years     2
9    0 - 1 year     1
10         <NA>  <NA>
11         <NA>  <NA>
13         <NA>  <NA>
14   0 - 1 year     1
15         <NA>  <NA>

In [50]:
cleaned_df["addi_rooms"] = pd.to_numeric(
    cleaned_df["additionalrooms"]
    .astype("string")
    .str.extract(r"^\s*(\d+)\s*rooms?", expand=False),
    errors="coerce"
)

display(cleaned_df[["additionalrooms", "addi_rooms"]].head(15))

                                    additionalrooms  addi_rooms
0                                              <NA>        <NA>
1                                              <NA>        <NA>
2                                              <NA>        <NA>
3                                              <NA>        <NA>
4                                              <NA>        <NA>
5                                              <NA>        <NA>
6                                              <NA>        <NA>
7                                              <NA>        <NA>
8   3 rooms( study room, servant room, pooja room )           3
9                                              <NA>        <NA>
10                                             <NA>        <NA>
11                                             <NA>        <NA>
13  3 rooms( study room, servant room, pooja room )           3
14                                             <NA>        <NA>
15                                             <NA>        <NA>

In [51]:
numeric_columns = ["balconies", "bathroom", "opensides"]

for column in numeric_columns:
    cleaned_df[column] = pd.to_numeric(
        cleaned_df[column],
        errors="coerce"
    )

display(cleaned_df[numeric_columns].dtypes.to_frame(name="Data Type"))

          Data Type
balconies     Int64
bathroom      Int64
opensides     Int64

In [52]:
cleaned_df["floor"] = pd.to_numeric(
    cleaned_df["floor"]
    .astype("string")
    .str.extract(r"(-?\d+(?:\.\d+)?)", expand=False),
    errors="coerce"
)

display(cleaned_df[["floor"]].head(15))

    floor
0       3
1       1
2       1
3       1
4       6
5       2
6       1
7       1
8       4
9       1
10      1
11      1
13     12
14      2
15     14

In [53]:
bhk_text = cleaned_df["bhk"].astype("string").str.strip()

bedrooms_bhk = pd.to_numeric(
    bhk_text.str.extract(r"(\d+)\s*BHK", expand=False),
    errors="coerce"
)

bedrooms_rk = pd.to_numeric(
    bhk_text.str.extract(r"(\d+)\s*RK", expand=False),
    errors="coerce"
)

cleaned_df["Bedrooms"] = bedrooms_bhk.fillna(bedrooms_rk)

display(cleaned_df[["bhk", "Bedrooms"]].head(20))

                bhk  Bedrooms
0   3 BHK Apartment         3
1   2 BHK Apartment         2
2   1 BHK Apartment         1
3   2 BHK Apartment         2
4   3 BHK Apartment         3
5   2 BHK Apartment         2
6   4 BHK Apartment         4
7   1 BHK Apartment         1
8   3 BHK Apartment         3
9   1 BHK Apartment         1
10  1 BHK Apartment         1
11  2 BHK Apartment         2
13  4 BHK Apartment         4
14  2 BHK Apartment         2
15  3 BHK Apartment         3
52  2 BHK Apartment         2
53  3 BHK Apartment         3
54  2 BHK Apartment         2
55  3 BHK Apartment         3
56  2 BHK Apartment         2

In [54]:
bhk_lower = cleaned_df["bhk"].astype("string").str.lower()

cleaned_df["Residential"] = np.where(
    bhk_lower.str.contains("residential plot", na=False),
    "yes",
    "no"
)

display(cleaned_df[["bhk", "Residential"]].head(15))

                bhk Residential
0   3 BHK Apartment          no
1   2 BHK Apartment          no
2   1 BHK Apartment          no
3   2 BHK Apartment          no
4   3 BHK Apartment          no
5   2 BHK Apartment          no
6   4 BHK Apartment          no
7   1 BHK Apartment          no
8   3 BHK Apartment          no
9   1 BHK Apartment          no
10  1 BHK Apartment          no
11  2 BHK Apartment          no
13  4 BHK Apartment          no
14  2 BHK Apartment          no
15  3 BHK Apartment          no

In [55]:
cleaned_df["Villa"] = np.where(
    bhk_lower.str.contains(r"\bvilla\b", na=False, regex=True),
    "yes",
    "no"
)

display(cleaned_df[["bhk", "Villa"]].head(15))

                bhk Villa
0   3 BHK Apartment    no
1   2 BHK Apartment    no
2   1 BHK Apartment    no
3   2 BHK Apartment    no
4   3 BHK Apartment    no
5   2 BHK Apartment    no
6   4 BHK Apartment    no
7   1 BHK Apartment    no
8   3 BHK Apartment    no
9   1 BHK Apartment    no
10  1 BHK Apartment    no
11  2 BHK Apartment    no
13  4 BHK Apartment    no
14  2 BHK Apartment    no
15  3 BHK Apartment    no

In [56]:
cleaned_df["Independent"] = np.where(
    bhk_lower.str.contains("independent", na=False),
    "yes",
    "no"
)

display(cleaned_df[["bhk", "Independent"]].head(15))

                bhk Independent
0   3 BHK Apartment          no
1   2 BHK Apartment          no
2   1 BHK Apartment          no
3   2 BHK Apartment          no
4   3 BHK Apartment          no
5   2 BHK Apartment          no
6   4 BHK Apartment          no
7   1 BHK Apartment          no
8   3 BHK Apartment          no
9   1 BHK Apartment          no
10  1 BHK Apartment          no
11  2 BHK Apartment          no
13  4 BHK Apartment          no
14  2 BHK Apartment          no
15  3 BHK Apartment          no

In [57]:
cleaned_df["Penthouse"] = np.where(
    bhk_lower.str.contains("penthouse", na=False),
    "yes",
    "no"
)

display(cleaned_df[["bhk", "Penthouse"]].head(15))

                bhk Penthouse
0   3 BHK Apartment        no
1   2 BHK Apartment        no
2   1 BHK Apartment        no
3   2 BHK Apartment        no
4   3 BHK Apartment        no
5   2 BHK Apartment        no
6   4 BHK Apartment        no
7   1 BHK Apartment        no
8   3 BHK Apartment        no
9   1 BHK Apartment        no
10  1 BHK Apartment        no
11  2 BHK Apartment        no
13  4 BHK Apartment        no
14  2 BHK Apartment        no
15  3 BHK Apartment        no

In [58]:
def create_apartment_description(bedrooms):
    if pd.isna(bedrooms):
        return np.nan

    bedrooms = int(bedrooms)

    bedroom_label = "Bedroom" if bedrooms == 1 else "Bedrooms"

    return f"{bedrooms} {bedroom_label}, 1 Hall, 1 Kitchen"


cleaned_df["Apartment"] = cleaned_df["Bedrooms"].apply(
    create_apartment_description
)

display(cleaned_df[["bhk", "Apartment", "Bedrooms"]].head(20))

                bhk                      Apartment  Bedrooms
0   3 BHK Apartment  3 Bedrooms, 1 Hall, 1 Kitchen         3
1   2 BHK Apartment  2 Bedrooms, 1 Hall, 1 Kitchen         2
2   1 BHK Apartment   1 Bedroom, 1 Hall, 1 Kitchen         1
3   2 BHK Apartment  2 Bedrooms, 1 Hall, 1 Kitchen         2
4   3 BHK Apartment  3 Bedrooms, 1 Hall, 1 Kitchen         3
5   2 BHK Apartment  2 Bedrooms, 1 Hall, 1 Kitchen         2
6   4 BHK Apartment  4 Bedrooms, 1 Hall, 1 Kitchen         4
7   1 BHK Apartment   1 Bedroom, 1 Hall, 1 Kitchen         1
8   3 BHK Apartment  3 Bedrooms, 1 Hall, 1 Kitchen         3
9   1 BHK Apartment   1 Bedroom, 1 Hall, 1 Kitchen         1
10  1 BHK Apartment   1 Bedroom, 1 Hall, 1 Kitchen         1
11  2 BHK Apartment  2 Bedrooms, 1 Hall, 1 Kitchen         2
13  4 BHK Apartment  4 Bedrooms, 1 Hall, 1 Kitchen         4
14  2 BHK Apartment  2 Bedrooms, 1 Hall, 1 Kitchen         2
15  3 BHK Apartment  3 Bedrooms, 1 Hall, 1 Kitchen         3
52  2 BHK Apartment  2 Bedrooms, 1 Hall, 1 Kitchen         2
53  3 BHK Apartment  3 Bedrooms, 1 Hall, 1 Kitchen         3
54  2 BHK Apartment  2 Bedrooms, 1 Hall, 1 Kitchen         2
55  3 BHK Apartment  3 Bedrooms, 1 Hall, 1 Kitchen         3
56  2 BHK Apartment  2 Bedrooms, 1 Hall, 1 Kitchen         2

In [59]:
amenity_columns = [
    "Lift Available",
    "Car Parking",
    "Power Backup",
    "24 X 7 Security",
    "Children play area",
    "Vaastu Compliant",
    "Club House",
    "Gymnasium",
    "Swimming Pool",
    "Sports Facility",
    "Indoor Games",
    "Jogging Track",
    "Maintenance Staff",
    "Intercom",
    "Golf Course",
    "Cafeteria",
    "Rain Water Harvesting",
    "Staff Quarter",
    "Multipurpose Room",
    "Landscaped Gardens",
    "Shopping Mall",
    "School",
    "Hospital",
    "ATM",
    "AC",
    "Wardrobe",
    "TV",
    "Refrigerator",
    "Sofa",
    "Washing Machine",
    "Wifi",
    "Microwave",
    "Dining Table",
    "Gas connection",
    "BED"
]

print("Total amenity columns:", len(amenity_columns))

Total amenity columns: 35

In [60]:

amenities_text = cleaned_df["amenitiesavailable"].astype("string")

for amenity in amenity_columns:

    found = amenities_text.str.contains(
        re.escape(amenity),
        case=False,
        regex=True,
        na=False
    )

    # Use pandas StringDtype to support strings and missing values
    cleaned_df[amenity] = pd.Series(
        np.select(
            [
                amenities_text.isna(),
                found
            ],
            [
                pd.NA,
                "yes"
            ],
            default="no"
        ),
        index=cleaned_df.index,
        dtype="string"
    )

display(cleaned_df[amenity_columns].head())

,Lift Available,Car Parking,Power Backup,24 X 7 Security,Children play area,Vaastu Compliant,Club House,Gymnasium,Swimming Pool,Sports Facility,...,Wardrobe,TV,Refrigerator,Sofa,Washing Machine,Wifi,Microwave,Dining Table,Gas connection,BED
0,yes,yes,yes,no,no,no,no,no,no,no,...,no,no,no,no,no,no,no,no,yes,no
1,yes,yes,yes,yes,no,yes,yes,yes,yes,no,...,no,no,no,no,no,no,no,no,no,no
2,yes,yes,yes,yes,no,yes,yes,yes,yes,no,...,no,no,no,no,no,no,no,no,no,no
3,yes,yes,yes,yes,no,yes,yes,yes,yes,no,...,no,no,no,no,no,no,no,no,no,no
4,yes,yes,yes,yes,no,no,no,yes,no,no,...,no,no,no,no,no,no,no,no,no,no

In [61]:
reference_columns = [
    "Unnamed: 0",
    "balconies",
    "bathroom",
    "facing",
    "floor",
    "locality",
    "neworold",
    "opensides",
    "price",
    "addi_rooms",
    "Age",
    "Lift Available",
    "Car Parking",
    "Power Backup",
    "24 X 7 Security",
    "Children play area",
    "Vaastu Compliant",
    "Club House",
    "Gymnasium",
    "Swimming Pool",
    "Sports Facility",
    "Indoor Games",
    "Jogging Track",
    "Maintenance Staff",
    "Intercom",
    "Golf Course",
    "Cafeteria",
    "Rain Water Harvesting",
    "Staff Quarter",
    "Multipurpose Room",
    "Landscaped Gardens",
    "Shopping Mall",
    "School",
    "Hospital",
    "ATM",
    "AC",
    "Wardrobe",
    "TV",
    "Refrigerator",
    "Sofa",
    "Washing Machine",
    "Wifi",
    "Microwave",
    "Dining Table",
    "Gas connection",
    "BED",
    "Area",
    "Residential",
    "Villa",
    "Independent",
    "Penthouse",
    "Apartment",
    "Bedrooms"
]

final_df = cleaned_df[reference_columns].copy()

print("Final dataset shape:", final_df.shape)
print("Number of columns:", len(final_df.columns))

display(final_df.head())

Final dataset shape: (27700, 53)
Number of columns: 53

,Unnamed: 0,balconies,bathroom,facing,floor,locality,neworold,opensides,price,addi_rooms,...,Dining Table,Gas connection,BED,Area,Residential,Villa,Independent,Penthouse,Apartment,Bedrooms
0,0,2,3,west,3,deccan gymkhana,new,2,27000000,<NA>,...,no,yes,no,1611,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3
1,1,<NA>,2,northeast,1,kharadi,new,<NA>,7610050,<NA>,...,no,no,no,1279,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2
2,2,<NA>,1,northeast,1,sus,new,<NA>,4100000,<NA>,...,no,no,no,670,no,no,no,no,"1 Bedroom, 1 Hall, 1 Kitchen",1
3,3,<NA>,2,northeast,1,bavdhan,new,<NA>,5736000,<NA>,...,no,no,no,956,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2
4,4,1,3,west,6,deccan gymkhana,new,2,29002000,<NA>,...,no,no,no,1706,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3

In [62]:
print("Final columns:")

for number, column in enumerate(final_df.columns, start=1):
    print(number, column)

assert len(final_df.columns) == 53
assert final_df.columns.tolist() == reference_columns

print("\nAll 53 columns are present in the required order.")

Final columns:
1 Unnamed: 0
2 balconies
3 bathroom
4 facing
5 floor
6 locality
7 neworold
8 opensides
9 price
10 addi_rooms
11 Age
12 Lift Available
13 Car Parking
14 Power Backup
15 24 X 7 Security
16 Children play area
17 Vaastu Compliant
18 Club House
19 Gymnasium
20 Swimming Pool
21 Sports Facility
22 Indoor Games
23 Jogging Track
24 Maintenance Staff
25 Intercom
26 Golf Course
27 Cafeteria
28 Rain Water Harvesting
29 Staff Quarter
30 Multipurpose Room
31 Landscaped Gardens
32 Shopping Mall
33 School
34 Hospital
35 ATM
36 AC
37 Wardrobe
38 TV
39 Refrigerator
40 Sofa
41 Washing Machine
42 Wifi
43 Microwave
44 Dining Table
45 Gas connection
46 BED
47 Area
48 Residential
49 Villa
50 Independent
51 Penthouse
52 Apartment
53 Bedrooms

All 53 columns are present in the required order.

In [64]:
final_df.to_csv(OUTPUT_PATH, index=False)

print("Cleaned dataset saved successfully!")
print("File location:", OUTPUT_PATH)
print("Final shape:", final_df.shape)

Cleaned dataset saved successfully!
File location: D:\Pune-House-Price-Prediction\data\processed\pune_cleaned_reference.csv
Final shape: (27700, 53)

In [65]:
verified_df = pd.read_csv(OUTPUT_PATH)

print("Saved file shape:", verified_df.shape)
print("Saved file columns:", len(verified_df.columns))

display(verified_df.head())

Saved file shape: (27700, 53)
Saved file columns: 53

,Unnamed: 0,balconies,bathroom,facing,floor,locality,neworold,opensides,price,addi_rooms,...,Dining Table,Gas connection,BED,Area,Residential,Villa,Independent,Penthouse,Apartment,Bedrooms
0,0,2.0,3.0,west,3.0,deccan gymkhana,new,2.0,27000000,NaN,...,no,yes,no,1611.0,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3.0
1,1,NaN,2.0,northeast,1.0,kharadi,new,NaN,7610050,NaN,...,no,no,no,1279.0,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2.0
2,2,NaN,1.0,northeast,1.0,sus,new,NaN,4100000,NaN,...,no,no,no,670.0,no,no,no,no,"1 Bedroom, 1 Hall, 1 Kitchen",1.0
3,3,NaN,2.0,northeast,1.0,bavdhan,new,NaN,5736000,NaN,...,no,no,no,956.0,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2.0
4,4,1.0,3.0,west,6.0,deccan gymkhana,new,2.0,29002000,NaN,...,no,no,no,1706.0,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3.0

In [66]:
REFERENCE_PATH = PROJECT_ROOT / "data" / "processed" / "Cleaned_pune_data.csv"

reference_df = pd.read_csv(REFERENCE_PATH)

print("Generated shape:", final_df.shape)
print("Reference shape:", reference_df.shape)

print("\nColumns only in generated file:")
print(sorted(set(final_df.columns) - set(reference_df.columns)))

print("\nColumns only in reference file:")
print(sorted(set(reference_df.columns) - set(final_df.columns)))

print("\nColumn order matches:", final_df.columns.tolist() == reference_df.columns.tolist())

Generated shape: (27700, 53)
Reference shape: (37517, 53)

Columns only in generated file:
[]

Columns only in reference file:
[]

Column order matches: True

In [67]:
comparison_columns = [
    "Unnamed: 0",
    "balconies",
    "bathroom",
    "facing",
    "floor",
    "locality",
    "neworold",
    "price",
    "addi_rooms",
    "Age",
    "Area",
    "Residential",
    "Villa",
    "Independent",
    "Penthouse",
    "Apartment",
    "Bedrooms"
]

print("Generated dataset:")
display(final_df[comparison_columns].head(10))

print("Reference dataset:")
display(reference_df[comparison_columns].head(10))

Generated dataset:

,Unnamed: 0,balconies,bathroom,facing,floor,locality,neworold,price,addi_rooms,Age,Area,Residential,Villa,Independent,Penthouse,Apartment,Bedrooms
0,0,2,3,west,3,deccan gymkhana,new,27000000,<NA>,3,1611,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3
1,1,<NA>,2,northeast,1,kharadi,new,7610050,<NA>,1,1279,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2
2,2,<NA>,1,northeast,1,sus,new,4100000,<NA>,1,670,no,no,no,no,"1 Bedroom, 1 Hall, 1 Kitchen",1
3,3,<NA>,2,northeast,1,bavdhan,new,5736000,<NA>,3,956,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2
4,4,1,3,west,6,deccan gymkhana,new,29002000,<NA>,1,1706,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3
5,5,2,2,northeast,2,mundhwa,new,4720765,<NA>,1,1015,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2
6,6,<NA>,5,northeast,1,viman nagar,new,30172500,<NA>,2,3725,no,no,no,no,"4 Bedrooms, 1 Hall, 1 Kitchen",4
7,7,<NA>,1,northeast,1,baner,new,4000000,<NA>,1,450,no,no,no,no,"1 Bedroom, 1 Hall, 1 Kitchen",1
8,8,2,3,west,4,law collage road,resale,24000000,3,2,1650,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3
9,9,1,1,northeast,1,mahalunge,new,2783351,<NA>,1,449,no,no,no,no,"1 Bedroom, 1 Hall, 1 Kitchen",1

Reference dataset:

,Unnamed: 0,balconies,bathroom,facing,floor,locality,neworold,price,addi_rooms,Age,Area,Residential,Villa,Independent,Penthouse,Apartment,Bedrooms
0,0,2.0,3.0,west,3.0,deccan gymkhana,new,27000000.0,NaN,3.0,1611.0,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3.0
1,1,NaN,2.0,northeast,1.0,kharadi,new,7610050.0,NaN,1.0,1279.0,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2.0
2,2,NaN,1.0,northeast,1.0,sus,new,4100000.0,NaN,1.0,670.0,no,no,no,no,"1 Bedrooms, 1 Hall, 1 Kitchen",1.0
3,3,NaN,2.0,northeast,1.0,bavdhan,new,5736000.0,NaN,3.0,956.0,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2.0
4,4,1.0,3.0,west,6.0,deccan gymkhana,new,29002000.0,NaN,1.0,1706.0,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3.0
5,5,2.0,2.0,northeast,2.0,mundhwa,new,4720765.0,NaN,1.0,1015.0,no,no,no,no,"2 Bedrooms, 1 Hall, 1 Kitchen",2.0
6,6,NaN,5.0,northeast,1.0,viman nagar,new,30172500.0,NaN,2.0,3725.0,no,no,no,no,"4 Bedrooms, 1 Hall, 1 Kitchen",4.0
7,7,NaN,1.0,northeast,1.0,baner,new,4000000.0,NaN,1.0,450.0,no,no,no,no,"1 Bedrooms, 1 Hall, 1 Kitchen",1.0
8,8,2.0,3.0,west,4.0,law collage road,old,24000000.0,3.0,2.0,1650.0,no,no,no,no,"3 Bedrooms, 1 Hall, 1 Kitchen",3.0
9,9,1.0,1.0,northeast,1.0,mahalunge,new,2783351.0,NaN,1.0,449.0,no,no,no,no,"1 Bedrooms, 1 Hall, 1 Kitchen",1.0

In [68]:
missing_summary = pd.DataFrame({
    "Missing Count": final_df.isna().sum(),
    "Missing Percentage": (final_df.isna().mean() * 100).round(2)
})

display(
    missing_summary.sort_values(
        by="Missing Count",
        ascending=False
    )
)

                       Missing Count  Missing Percentage
addi_rooms                     20064               72.43
opensides                      18075               65.25
balconies                      10541               38.05
Age                             6847               24.72
floor                           3177               11.47
facing                          2176                7.86
Gymnasium                       2024                7.31
Club House                      2024                7.31
Lift Available                  2024                7.31
Car Parking                     2024                7.31
Children play area              2024                7.31
24 X 7 Security                 2024                7.31
Power Backup                    2024                7.31
Sports Facility                 2024                7.31
Vaastu Compliant                2024                7.31
Swimming Pool                   2024                7.31
Golf Course                     2024                7.31
Intercom                        2024                7.31
Maintenance Staff               2024                7.31
Jogging Track                   2024                7.31
Indoor Games                    2024                7.31
TV                              2024                7.31
Refrigerator                    2024                7.31
Sofa                            2024                7.31
Washing Machine                 2024                7.31
Wifi                            2024                7.31
Cafeteria                       2024                7.31
Rain Water Harvesting           2024                7.31
Staff Quarter                   2024                7.31
Multipurpose Room               2024                7.31
Landscaped Gardens              2024                7.31
Shopping Mall                   2024                7.31
School                          2024                7.31
Hospital                        2024                7.31
ATM                             2024                7.31
AC                              2024                7.31
Wardrobe                        2024                7.31
BED                             2024                7.31
Microwave                       2024                7.31
Dining Table                    2024                7.31
Gas connection                  2024                7.31
bathroom                         276                1.00
Area                              17                0.06
Apartment                          8                0.03
Bedrooms                           8                0.03
locality                           0                0.00
price                              0                0.00
neworold                           0                0.00
Unnamed: 0                         0                0.00
Villa                              0                0.00
Residential                        0                0.00
Penthouse                          0                0.00
Independent                        0                0.00

In [69]:
print("=" * 50)
print("PUNE PROPERTY DATA CLEANING SUMMARY")
print("=" * 50)

print("Original dataset rows:", len(df))
print("Cleaned dataset rows:", len(final_df))
print("Final columns:", len(final_df.columns))
print("Duplicate rows:", final_df.duplicated().sum())
print("Missing price values:", final_df["price"].isna().sum())
print("Saved file:", OUTPUT_PATH)

display(final_df.describe(include="all").T)

==================================================
PUNE PROPERTY DATA CLEANING SUMMARY
==================================================
Original dataset rows: 37539
Cleaned dataset rows: 27700
Final columns: 53
Duplicate rows: 0
Missing price values: 0
Saved file: D:\Pune-House-Price-Prediction\data\processed\pune_cleaned_reference.csv

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,27700.0,NaN,NaN,NaN,18464.37083,10800.159644,0.0,8903.75,18080.5,28349.25,37538.0
balconies,17159.0,<NA>,<NA>,<NA>,1.731861,0.744929,1.0,1.0,2.0,2.0,7.0
bathroom,27424.0,<NA>,<NA>,<NA>,2.551305,1.052566,1.0,2.0,2.0,3.0,8.0
facing,25524,8,east,17128,NaN,NaN,NaN,NaN,NaN,NaN,NaN
floor,24523.0,<NA>,<NA>,<NA>,5.101211,3.225801,1.0,3.0,5.0,7.0,34.0
locality,27700,378,kharadi,3908,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neworold,27700,2,resale,19429,NaN,NaN,NaN,NaN,NaN,NaN,NaN
opensides,9625.0,<NA>,<NA>,<NA>,2.290805,1.20839,1.0,1.0,2.0,4.0,4.0
price,27700,2208,7500000,649,NaN,NaN,NaN,NaN,NaN,NaN,NaN
addi_rooms,7636.0,<NA>,<NA>,<NA>,1.364196,0.615684,1.0,1.0,1.0,2.0,3.0
Age,20853.0,<NA>,<NA>,<NA>,7.011125,4.534654,1.0,3.0,6.0,11.0,42.0
Lift Available,25676,2,yes,22337,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Car Parking,25676,2,yes,23539,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Power Backup,25676,2,yes,22940,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24 X 7 Security,25676,2,yes,23156,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Children play area,25676,1,no,25676,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vaastu Compliant,25676,2,yes,16811,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Club House,25676,2,yes,16138,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gymnasium,25676,2,yes,16735,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Swimming Pool,25676,2,yes,17714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sports Facility,25676,2,no,20277,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indoor Games,25676,2,no,19469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jogging Track,25676,2,yes,17605,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Maintenance Staff,25676,2,no,18192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Intercom,25676,2,no,16929,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Golf Course,25676,2,no,24659,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cafeteria,25676,2,no,23376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rain Water Harvesting,25676,2,yes,15889,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Staff Quarter,25676,2,no,15860,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Multipurpose Room,25676,2,no,18822,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Landscaped Gardens,25676,2,yes,14526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shopping Mall,25676,2,no,18247,NaN,NaN,NaN,NaN,NaN,NaN,NaN
School,25676,2,no,18396,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospital,25676,2,no,18458,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ATM,25676,2,no,17924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AC,25676,2,yes,24186,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wardrobe,25676,2,no,22475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TV,25676,2,no,24711,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Refrigerator,25676,2,no,24242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sofa,25676,2,no,22819,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Washing Machine,25676,2,no,24233,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wifi,25676,2,no,24858,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Microwave,25676,2,no,25327,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dining Table,25676,2,no,23460,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gas connection,25676,2,no,22627,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BED,25676,2,no,22043,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area,27683.0,<NA>,<NA>,<NA>,1681.934617,1126.653366,220.0,1000.0,1314.0,1950.0,19000.0
Residential,27700,2,no,27692,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Villa,27700,2,no,26188,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Independent,27700,2,no,26985,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Penthouse,27700,2,no,27594,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Apartment,27692,8,"2 Bedrooms, 1 Hall, 1 Kitchen",10843,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bedrooms,27692.0,<NA>,<NA>,<NA>,2.558573,0.958004,1.0,2.0,2.0,3.0,8.0

In [70]:
print("Raw dataset shape:", df.shape)
print("After cleaning shape:", cleaned_df.shape)
print("Final dataset shape:", final_df.shape)

print("\nRows removed in Cell 6:", len(df) - len(cleaned_df))
print("Rows lost during final column selection:", len(cleaned_df) - len(final_df))

print("\nReference dataset shape:")
print(reference_df.shape if "reference_df" in globals() else "Reference file not loaded")

Raw dataset shape: (37539, 24)
After cleaning shape: (27700, 68)
Final dataset shape: (27700, 53)

Rows removed in Cell 6: 9839
Rows lost during final column selection: 0

Reference dataset shape:
(37517, 53)