# Pune House Price Prediction — Data Cleaning

## 1. Project Objective
The objective of this notebook is to inspect, clean, and validate the raw Pune property dataset before performing exploratory data analysis and developing machine learning models.

## 2. Data Cleaning Workflow
- Inspect the dataset structure and dimensions.
- Identify missing values and duplicate records.
- Examine data types and inconsistent values.
- Investigate invalid records and potential outliers.
- Apply appropriate cleaning techniques.
- Validate and save the cleaned dataset.

**Important:** The original raw dataset will remain unchanged. All cleaning operations will be performed on a separate working copy.

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:,.2f}".format)

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.6
NumPy version: 2.5.4

In [3]:
project_root = Path.cwd().parent
raw_file = project_root / "data" / "raw" / "Pune_property_data.csv"

print("Project folder:", project_root)
print("Dataset path:", raw_file)
print("File exists:", raw_file.exists())

Project folder: d:\Pune-House-Price-Prediction
Dataset path: d:\Pune-House-Price-Prediction\data\raw\Pune_property_data.csv
File exists: True

In [4]:
df = pd.read_csv(raw_file)

# Keep the original DataFrame unchanged.
# All cleaning will be done on this working copy.
df_clean = df.copy(deep=True)

print("Dataset loaded successfully!")
print("Original shape:", df.shape)

Dataset loaded successfully!
Original shape: (37539, 24)

In [5]:
display(df.head())

,Unnamed: 0,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
0,0,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,Indoor...","24 X 7 Security,Children's play area,Club Hous...","1,611 sq ft",2,3,3 BHK Apartment,1209 sq ft,West,"3,",Deccan Gymkhana,New,2,Road View,Co-Operative Society,NaN,27000000,"₹ 16,759/ sq ft",Bhansali Prive Rio,40 feet,Ready to move,6
1,1,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","Children's play area,Sports Facility,Landscape...","1,279 sq ft",NaN,2,2 BHK Apartment,NaN,NorthEast,1,Kharadi,New,NaN,NaN,Freehold,NaN,7610050,"₹ 5,950/ sq ft",Goel Ganga Platino,NaN,Ready to move,NaN
2,2,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...",Sports Facility,670 sq ft,NaN,1,1 BHK Apartment,NaN,NorthEast,1,Sus,New,NaN,NaN,Freehold,NaN,4100000,"₹ 6,119/ sq ft",Vilas Javdekar Yashwin,NaN,Ready to move,NaN
3,3,NaN,2 - 3 years,"Lift Available,Car Parking,Power Backup,24 X 7...","Sports Facility,Landscaped Gardens",956 sq ft,NaN,2,2 BHK Apartment,615 sq ft,NorthEast,1,Bavdhan,New,NaN,NaN,Freehold,NaN,5736000,"₹ 6,000/ sq ft",Rohan Ishan,NaN,Ready to move,NaN
4,4,NaN,0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","Club House,Swimming Pool,Sports Facility,Joggi...","1,706 sq ft",1,3,3 BHK Apartment,1195 sq ft,West,"6,",Deccan Gymkhana,New,2,Road View,Freehold,NaN,29002000,"₹ 17,000/ sq ft",Swojas Aavishkar,60 feet,Ready to move,9

In [6]:
display(df.tail())

,Unnamed: 0,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
37534,37534,1 rooms( pooja room ),0 - 1 year,"Lift Available,Car Parking,Power Backup,24 X 7...","Children's play area,Club House,Gymnasium,Spor...","1,084 sq ft",1,2,2 BHK Apartment,814 sq ft,East,"6,",Baner,New,4,Garden View,Freehold,NaN,8363000,"₹ 7,714/ sq ft",Builder Luxurious Apartment,NaN,Ready to move,12
37535,37535,1 rooms( pooja room ),NaN,"Lift Available,Car Parking,Power Backup,24 X 7...","Children's play area,Club House,Gymnasium,Spor...",953 sq ft,1,2,2 BHK Apartment,706 sq ft,East,"7,",Wakad,New,4,Garden View,Freehold,01-12-2019,6338000,"₹ 6,650/ sq ft",Builder Luxurious Apartment,NaN,Under Construction,12
37536,37536,1 rooms( pooja room ),NaN,"Lift Available,Car Parking,Power Backup,24 X 7...","Children's play area,Club House,Gymnasium,Spor...","1,218 sq ft",1,2,2 BHK Apartment,901 sq ft,East,"6,",Hinjewadi,New,4,Garden View,Freehold,01-12-2020,8100000,"₹ 6,650/ sq ft",Builder Luxurious Apartment,NaN,Under Construction,12
37537,37537,1 rooms( pooja room ),NaN,"Lift Available,Car Parking,Power Backup,24 X 7...","Children's play area,Club House,Gymnasium,Spor...","1,074 sq ft",1,2,2 BHK Apartment,796 sq ft,East,"6,",Bavdhan,New,4,Garden View,Freehold,01-12-2018,7780000,"₹ 7,243/ sq ft",Builder Luxurious Apartment,NaN,Under Construction,12
37538,37538,"2 rooms( servant room, pooja room )",NaN,"Lift Available,Car Parking,Power Backup,24 X 7...","Children's play area,Club House,Gymnasium,Spor...","4,561 sq ft",2,4,4 BHK Apartment,3379 sq ft,West,"6,",Aundh,New,4,Garden View,Freehold,01-06-2018,47800000,"₹ 10,480/ sq ft",Builder Luxurious Apartment,NaN,Under Construction,12

In [7]:
print(f"Total rows: {df.shape[0]:,}")
print(f"Total columns: {df.shape[1]}")

Total rows: 37,539
Total columns: 24

In [8]:
print(df.columns.tolist())

['Unnamed: 0', 'additionalrooms', 'age', 'amenitiesavailable', 'amenitiesnot', 'area', 'balconies', 'bathroom', 'bhk', 'carpetarea', 'facing', 'floor', 'locality', 'neworold', 'opensides', 'overlooking', 'ownership', 'possesiondate', 'price', 'pricepersquare', 'projectname', 'roadfaceing', 'status', 'totalfloor']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37539 entries, 0 to 37538
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          37539 non-null  int64
 1   additionalrooms     9321 non-null   str
 2   age                 27637 non-null  str
 3   amenitiesavailable  34445 non-null  str
 4   amenitiesnot        34286 non-null  str
 5   area                37518 non-null  str
 6   balconies           21911 non-null  str
 7   bathroom            34667 non-null  str
 8   bhk                 37538 non-null  str
 9   carpetarea          8622 non-null   str
 10  facing              30919 non-null  str
 11  floor               31919 non-null  str
 12  locality            37538 non-null  str
 13  neworold            37538 non-null  str
 14  opensides           11605 non-null  str
 15  overlooking         17140 non-null  str
 16  ownership           28156 non-null  str
 17  possesiondate       4736 non-null   str
 18  price               37538 non-null  str
 19  pricepersquare      37538 non-null  str
 20  projectname         24129 non-null  str
 21  roadfaceing         6875 non-null   str
 22  status              36078 non-null  str
 23  totalfloor          24114 non-null  str
dtypes: int64(1), str(23)
memory usage: 20.3 MB

In [10]:
display(df.describe())

       Unnamed: 0
count   37,539.00
mean    18,769.00
std     10,836.72
min          0.00
25%      9,384.50
50%     18,769.00
75%     28,153.50
max     37,538.00

In [11]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unnamed: 0,"37,539.00",NaN,NaN,NaN,"18,769.00","10,836.72",0.00,"9,384.50","18,769.00","28,153.50","37,538.00"
additionalrooms,9321,8,1 rooms( pooja room ),3440,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,27637,69,6 - 7 years,3552,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amenitiesavailable,34445,6402,"Lift Available,Car Parking,Power Backup,24 X 7...",1052,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amenitiesnot,34286,2534,Sports Facility,4659,NaN,NaN,NaN,NaN,NaN,NaN,NaN
area,37518,2380,"1,000 sq ft",700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
balconies,21911,9,1,9482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bathroom,34667,10,2,13705,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bhk,37538,40,2 BHK Apartment,13779,NaN,NaN,NaN,NaN,NaN,NaN,NaN
carpetarea,8622,1232,500 sq ft,151,NaN,NaN,NaN,NaN,NaN,NaN,NaN
facing,30919,9,East,20783,NaN,NaN,NaN,NaN,NaN,NaN,NaN
floor,31919,56,"3,",2921,NaN,NaN,NaN,NaN,NaN,NaN,NaN
locality,37538,503,Kharadi,5124,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neworold,37538,3,Resale,25860,NaN,NaN,NaN,NaN,NaN,NaN,NaN
opensides,11605,5,1,4199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
overlooking,17140,16,Garden View,4544,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ownership,28156,5,Freehold,25366,NaN,NaN,NaN,NaN,NaN,NaN,NaN
possesiondate,4736,52,01-12-2018,1445,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,37538,3342,7500000,817,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pricepersquare,37538,7086,"₹ 10,000/ sq ft",462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
projectname,24129,3591,Builder Luxurious Apartment,1620,NaN,NaN,NaN,NaN,NaN,NaN,NaN
roadfaceing,6875,84,20 feet,1054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,36078,12,"Ready to move,Unfurnished",16641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
totalfloor,24114,35,12,5482,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
missing_report = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percentage": (df.isna().mean() * 100).round(2),
    "unique_values": df.nunique(dropna=True),
    "data_type": df.dtypes.astype(str)
})

missing_report = missing_report.sort_values(
    by="missing_percentage",
    ascending=False
)

display(missing_report)

                    missing_count  missing_percentage  unique_values data_type
possesiondate               32803               87.38             52       str
roadfaceing                 30664               81.69             84       str
carpetarea                  28917               77.03           1232       str
additionalrooms             28218               75.17              8       str
opensides                   25934               69.09              5       str
overlooking                 20399               54.34             16       str
balconies                   15628               41.63              9       str
totalfloor                  13425               35.76             35       str
projectname                 13410               35.72           3591       str
age                          9902               26.38             69       str
ownership                    9383               25.00              5       str
facing                       6620               17.63              9       str
floor                        5620               14.97             56       str
amenitiesnot                 3253                8.67           2534       str
amenitiesavailable           3094                8.24           6402       str
bathroom                     2872                7.65             10       str
status                       1461                3.89             12       str
area                           21                0.06           2380       str
Unnamed: 0                      0                0.00          37539     int64
bhk                             1                0.00             40       str
locality                        1                0.00            503       str
neworold                        1                0.00              3       str
pricepersquare                  1                0.00           7086       str
price                           1                0.00           3342       str

In [13]:
duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)
print("Total records:", len(df))

Exact duplicate rows: 0
Total records: 37539

In [14]:
print("First 10 index values:")
display(df["Unnamed: 0"].head(10))

print("Last 10 index values:")
display(df["Unnamed: 0"].tail(10))

expected_index = np.arange(len(df))

print(
    "Is this just a sequential row index?",
    np.array_equal(df["Unnamed: 0"].to_numpy(), expected_index)
)

First 10 index values:

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Unnamed: 0, dtype: int64

Last 10 index values:

37529    37529
37530    37530
37531    37531
37532    37532
37533    37533
37534    37534
37535    37535
37536    37536
37537    37537
37538    37538
Name: Unnamed: 0, dtype: int64

Is this just a sequential row index? True

In [15]:
important_columns = [
    "price",
    "pricepersquare",
    "area",
    "carpetarea",
    "bhk",
    "bathroom",
    "balconies",
    "age",
    "floor",
    "totalfloor",
]

for column in important_columns:
    print(f"\n{'=' * 60}")
    print(f"Column: {column}")
    print("Data type:", df[column].dtype)
    print("Sample values:")
    display(df[column].dropna().drop_duplicates().head(15))

============================================================
Column: price
Data type: str
Sample values:

0     27000000
1      7610050
2      4100000
3      5736000
4     29002000
5      4720765
6     30172500
7      4000000
8     24000000
9      2783351
10     3281250
11     4725000
12    20300000
13    18000000
14     9000000
Name: price, dtype: str

============================================================
Column: pricepersquare
Data type: str
Sample values:

0     ₹ 16,759/ sq ft
1      ₹ 5,950/ sq ft
2      ₹ 6,119/ sq ft
3      ₹ 6,000/ sq ft
4     ₹ 17,000/ sq ft
5      ₹ 4,651/ sq ft
6      ₹ 8,100/ sq ft
7      ₹ 8,889/ sq ft
8     ₹ 14,545/ sq ft
9      ₹ 6,199/ sq ft
10     ₹ 5,250/ sq ft
12    ₹ 18,454/ sq ft
13     ₹ 5,454/ sq ft
14     ₹ 6,896/ sq ft
15     ₹ 6,133/ sq ft
Name: pricepersquare, dtype: str

============================================================
Column: area
Data type: str
Sample values:

0     1,611 sq ft
1     1,279 sq ft
2       670 sq ft
3       956 sq ft
4     1,706 sq ft
5     1,015 sq ft
6     3,725 sq ft
7       450 sq ft
8     1,650 sq ft
9       449 sq ft
10      625 sq ft
11      900 sq ft
12    1,100 sq ft
13    3,300 sq ft
14    1,305 sq ft
Name: area, dtype: str

============================================================
Column: carpetarea
Data type: str
Sample values:

0     1209 sq ft
3      615 sq ft
4     1195 sq ft
8     1150 sq ft
12     920 sq ft
13    2600 sq ft
14     966 sq ft
15    1085 sq ft
16     700 sq ft
40     780 sq ft
47     805 sq ft
53    1050 sq ft
54    1000 sq ft
55    1450 sq ft
59     465 sq ft
Name: carpetarea, dtype: str

============================================================
Column: bhk
Data type: str
Sample values:

0              3 BHK Apartment
1              2 BHK Apartment
2              1 BHK Apartment
6              4 BHK Apartment
23            Residential Plot
27              1 RK Apartment
48                 3 BHK Villa
92                 5 BHK Villa
282    4 BHK Independent House
389                4 BHK Villa
402    2 BHK Independent House
416    3 BHK Independent House
516    3 BHK Independent Floor
663                1 BHK Villa
794            4 BHK penthouse
Name: bhk, dtype: str

============================================================
Column: bathroom
Data type: str
Sample values:

0               3
1               2
2               1
6               5
78              4
750             6
1853     bathroom
4668            8
5515            7
20298           9
Name: bathroom, dtype: str

============================================================
Column: balconies
Data type: str
Sample values:

0                2
4                1
13               3
141              4
1853     balconies
4668             6
5013             5
17134            8
17964            7
Name: balconies, dtype: str

============================================================
Column: age
Data type: str
Sample values:

0       2 - 3 years
1        0 - 1 year
6       1 - 2 years
21      6 - 7 years
26          2 years
29      3 - 4 years
30    10 - 11 years
31      7 - 8 years
33      4 - 5 years
37      5 - 6 years
41    12 - 13 years
42    11 - 12 years
47           1 year
60         17 years
61          6 years
Name: age, dtype: str

============================================================
Column: floor
Data type: str
Sample values:

0      3,
1        1
4      6,
5      2,
8      4,
9      1,
13    12,
15    14,
53     7,
55    10,
59     8,
67     9,
69    11,
70     5,
81    16,
Name: floor, dtype: str

============================================================
Column: totalfloor
Data type: str
Sample values:

0      6
4      9
5     10
9     15
10    27
12     5
13    12
15    21
27     3
52     4
53    13
56    23
57    24
62    16
68    31
Name: totalfloor, dtype: str

In [16]:
text_columns = df.select_dtypes(include=["object", "str", "string"]).columns

missing_markers = [
    "",
    "-",
    "NA",
    "N/A",
    "NaN",
    "None",
    "null",
    "Not Available",
    "Not available",
]

for column in text_columns:
    values = df[column].dropna().astype(str).str.strip()

    matches = values[values.isin(missing_markers)]

    if not matches.empty:
        print(f"\nColumn: {column}")
        display(matches.value_counts())

In [17]:
categorical_columns = [
    "locality",
    "neworold",
    "status",
    "ownership",
    "facing",
    "roadfaceing",
]

for column in categorical_columns:
    print(f"\n{'=' * 60}")
    print(f"Column: {column}")
    display(
        df[column]
        .dropna()
        .astype(str)
        .str.strip()
        .value_counts()
        .head(20)
    )

============================================================
Column: locality

locality
Kharadi                    5124
Viman Nagar                3517
Kalyani Nagar              3382
Wagholi                    3150
Koregaon Park              2641
Hadapsar                   1762
Baner                      1329
Hinjewadi                  1134
Wakad                      1079
Bavdhan                     855
Undri                       777
Boat Club Road              773
Balewadi                    619
Wadgaon Sheri               577
Mundhwa                     493
Sangamvadi                  401
Dhayari                     366
NIBM Annex Mohammadwadi     327
Kondhwa                     317
Aundh                       315
Name: count, dtype: int64

============================================================
Column: neworold

neworold
Resale      25860
New         11656
neworold       22
Name: count, dtype: int64

============================================================
Column: status

status
Ready to move,Unfurnished            16641
Under Construction                    5287
Ready to move                         4927
Ready to move,Semi-Furnished          4636
Ready to move,Furnished               3571
Unfurnished                            446
Under Construction,Unfurnished         406
Under Construction,Semi-Furnished       75
Furnished                               41
status                                  22
Semi-Furnished                          21
Under Construction,Furnished             5
Name: count, dtype: int64

============================================================
Column: ownership

ownership
Freehold                25366
Co-Operative Society     2616
Leasehol                  105
Power of Attorney          47
ownership                  22
Name: count, dtype: int64

============================================================
Column: facing

facing
East         20783
North         3586
West          3565
NorthEast     1932
South          526
NorthWest      289
SouthEast      126
SouthWest       90
facing          22
Name: count, dtype: int64

============================================================
Column: roadfaceing

roadfaceing
20 feet     1054
40 feet      826
50 feet      814
30 feet      796
100 feet     654
60 feet      450
25 feet      350
80 feet      315
200 feet     249
15 feet      201
10 feet      187
90 feet      148
35 feet       97
45 feet       73
18 feet       73
120 feet      69
150 feet      44
328 feet      39
65 feet       37
14 feet       27
Name: count, dtype: int64

3.1 Identify Invalid and Repeated Header Rows

In [18]:
suspect_columns = ["neworold", "status", "ownership"]

suspect_masks = {}

for column in suspect_columns:
    suspect_masks[column] = (
        df[column]
        .astype("string")
        .str.strip()
        .str.casefold()
        .eq(column.casefold())
        .fillna(False)
    )

    print(
        f"{column}:",
        int(suspect_masks[column].sum()),
        "suspicious records"
    )

combined_suspect_mask = pd.DataFrame(suspect_masks).any(axis=1)

print("\nTotal records matching at least one suspicious label:",
      int(combined_suspect_mask.sum()))

print("\nSuspicious records:")
display(df.loc[combined_suspect_mask, suspect_columns].head(30))

neworold: 22 suspicious records
status: 22 suspicious records
ownership: 22 suspicious records

Total records matching at least one suspicious label: 22

Suspicious records:

       neworold  status  ownership
1853   neworold  status  ownership
3707   neworold  status  ownership
5480   neworold  status  ownership
7237   neworold  status  ownership
8850   neworold  status  ownership
10361  neworold  status  ownership
12072  neworold  status  ownership
13640  neworold  status  ownership
15285  neworold  status  ownership
16914  neworold  status  ownership
18460  neworold  status  ownership
19981  neworold  status  ownership
21488  neworold  status  ownership
23137  neworold  status  ownership
24913  neworold  status  ownership
26449  neworold  status  ownership
28251  neworold  status  ownership
30006  neworold  status  ownership
31676  neworold  status  ownership
33408  neworold  status  ownership
35161  neworold  status  ownership
36788  neworold  status  ownership

In [19]:
display(df.loc[combined_suspect_mask].head(30))

,Unnamed: 0,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
1853,1853,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
3707,3707,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
5480,5480,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
7237,7237,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
8850,8850,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
10361,10361,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
12072,12072,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
13640,13640,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
15285,15285,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
16914,16914,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
18460,18460,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
19981,19981,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
21488,21488,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
23137,23137,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
24913,24913,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
26449,26449,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
28251,28251,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
30006,30006,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
31676,31676,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
33408,33408,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
35161,35161,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor
36788,36788,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor

In [20]:
df_clean = df.copy(deep=True)

# Remove the sequential exported row index
df_clean = df_clean.drop(columns=["Unnamed: 0"])

# Remove leading/trailing whitespace from text values
text_columns = df_clean.select_dtypes(
    include=["object", "str", "string"]
).columns

for column in text_columns:
    df_clean[column] = df_clean[column].str.strip()

print("Shape after removing index column:", df_clean.shape)

Shape after removing index column: (37539, 23)

In [21]:
missing_markers = [
    "",
    "-",
    "NA",
    "N/A",
    "NaN",
    "None",
    "null",
    "Not Available",
    "Not available",
]

for column in df_clean.select_dtypes(
    include=["object", "str", "string"]
).columns:
    values = df_clean[column].astype("string").str.strip()

    df_clean[column] = values.mask(
        values.isin(missing_markers),
        pd.NA
    )

print("Blank and recognized placeholder values standardized.")

Blank and recognized placeholder values standardized.

3.2 Clean Numeric Features

In [22]:
# Price: values such as "27000000"
df_clean["price"] = pd.to_numeric(
    df_clean["price"].str.replace(",", "", regex=False),
    errors="coerce"
)

# Area: values such as "1,611 sq ft"
df_clean["area"] = pd.to_numeric(
    df_clean["area"]
    .str.replace(",", "", regex=False)
    .str.extract(r"(\d+(?:\.\d+)?)", expand=False),
    errors="coerce"
)

# Carpet area: values such as "1209 sq ft"
df_clean["carpetarea"] = pd.to_numeric(
    df_clean["carpetarea"]
    .str.replace(",", "", regex=False)
    .str.extract(r"(\d+(?:\.\d+)?)", expand=False),
    errors="coerce"
)

# Price per square foot: values such as "₹ 16,759/ sq ft"
df_clean["pricepersquare"] = pd.to_numeric(
    df_clean["pricepersquare"]
    .str.replace(",", "", regex=False)
    .str.extract(r"(\d+(?:\.\d+)?)", expand=False),
    errors="coerce"
)

print(df_clean[[
    "price",
    "pricepersquare",
    "area",
    "carpetarea"
]].dtypes)

display(df_clean[[
    "price",
    "pricepersquare",
    "area",
    "carpetarea"
]].head(10))

price             Int64
pricepersquare    Int64
area              Int64
carpetarea        Int64
dtype: object

      price  pricepersquare  area  carpetarea
0  27000000           16759  1611        1209
1   7610050            5950  1279        <NA>
2   4100000            6119   670        <NA>
3   5736000            6000   956         615
4  29002000           17000  1706        1195
5   4720765            4651  1015        <NA>
6  30172500            8100  3725        <NA>
7   4000000            8889   450        <NA>
8  24000000           14545  1650        1150
9   2783351            6199   449        <NA>

In [23]:
bhk_text = df_clean["bhk"].astype("string").str.strip()

df_clean["bhk_count"] = pd.to_numeric(
    bhk_text.str.extract(r"(\d+)\s*(?:BHK|RK)\b", flags=2, expand=False),
    errors="coerce"
)

df_clean["property_type"] = (
    bhk_text
    .str.replace(r"^\s*\d+\s*(?:BHK|RK)\s*", "", regex=True, case=False)
    .str.strip()
)

df_clean.loc[
    df_clean["property_type"].eq(""),
    "property_type"
] = pd.NA

display(df_clean[["bhk", "bhk_count", "property_type"]].head(20))

                bhk  bhk_count property_type
0   3 BHK Apartment          3     Apartment
1   2 BHK Apartment          2     Apartment
2   1 BHK Apartment          1     Apartment
3   2 BHK Apartment          2     Apartment
4   3 BHK Apartment          3     Apartment
5   2 BHK Apartment          2     Apartment
6   4 BHK Apartment          4     Apartment
7   1 BHK Apartment          1     Apartment
8   3 BHK Apartment          3     Apartment
9   1 BHK Apartment          1     Apartment
10  1 BHK Apartment          1     Apartment
11  2 BHK Apartment          2     Apartment
12  2 BHK Apartment          2     Apartment
13  4 BHK Apartment          4     Apartment
14  2 BHK Apartment          2     Apartment
15  3 BHK Apartment          3     Apartment
16  2 BHK Apartment          2     Apartment
17  1 BHK Apartment          1     Apartment
18  1 BHK Apartment          1     Apartment
19  2 BHK Apartment          2     Apartment

In [24]:
print("Original rows:", len(df))
print("Current rows:", len(df_clean))
print("Current columns:", len(df_clean.columns))

print("\nMissing values in converted columns:")
display(
    df_clean[[
        "price",
        "pricepersquare",
        "area",
        "carpetarea",
        "bhk_count"
    ]].isna().sum().to_frame("missing_count")
)

print("\nNumeric summaries:")
display(
    df_clean[[
        "price",
        "pricepersquare",
        "area",
        "carpetarea",
        "bhk_count"
    ]].describe().T
)

Original rows: 37539
Current rows: 37539
Current columns: 25

Missing values in converted columns:

                missing_count
price                      23
pricepersquare             23
area                       43
carpetarea              28939
bhk_count                1270

Numeric summaries:

,count,mean,std,min,25%,50%,75%,max
price,"37,516.00","14,745,248.32","17,104,214.67","100,000.00","5,600,000.00","8,589,950.00","16,000,000.00","269,000,000.00"
pricepersquare,"37,516.00","7,676.41","3,750.37",100.00,"5,465.00","6,823.00","8,992.00","91,549.00"
area,"37,496.00","1,870.06","2,580.41",150.00,982.00,"1,300.00","2,000.00","60,000.00"
carpetarea,"8,600.00","1,036.67",628.99,100.00,660.00,881.00,"1,190.00","7,104.00"
bhk_count,"36,269.00",2.53,0.97,0.00,2.00,2.00,3.00,8.00

In [25]:
suspect_columns = ["neworold", "status", "ownership"]

suspect_masks = {}

for column in suspect_columns:
    suspect_masks[column] = (
        df_clean[column]
        .astype("string")
        .str.strip()
        .str.casefold()
        .eq(column.casefold())
        .fillna(False)
    )

suspect_report = pd.DataFrame(suspect_masks)

print("Matches by column:")
display(suspect_report.sum().to_frame("count"))

combined_suspect_mask = suspect_report.any(axis=1)

print("Rows matching at least one suspicious label:",
      int(combined_suspect_mask.sum()))

display(df_clean.loc[combined_suspect_mask].head(30))

Matches by column:

           count
neworold      22
status        22
ownership     22

Rows matching at least one suspicious label: 22

,additionalrooms,age,amenitiesavailable,amenitiesnot,area,balconies,bathroom,bhk,carpetarea,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,price,pricepersquare,projectname,roadfaceing,status,totalfloor,bhk_count,property_type
1853,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
3707,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
5480,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
7237,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
8850,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
10361,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
12072,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
13640,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
15285,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
16914,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
18460,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
19981,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
21488,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
23137,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
24913,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
26449,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
28251,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
30006,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
31676,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
33408,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
35161,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk
36788,additionalrooms,age,amenitiesavailable,amenitiesnot,<NA>,balconies,bathroom,bhk,<NA>,facing,floor,locality,neworold,opensides,overlooking,ownership,possesiondate,<NA>,<NA>,projectname,roadfaceing,status,totalfloor,<NA>,bhk

In [26]:
for column in ["price", "pricepersquare", "area"]:
    print(f"\n--- {column}: original values now missing after conversion ---")

    failed_mask = df_clean[column].isna() & df[column].notna()

    display(
        df.loc[failed_mask, [column]]
        .drop_duplicates()
        .head(30)
    )

--- price: original values now missing after conversion ---

      price
1853  price

--- pricepersquare: original values now missing after conversion ---

      pricepersquare
1853  pricepersquare

--- area: original values now missing after conversion ---

      area
1853  area

In [27]:
display(
    df_clean.loc[
        df_clean["bhk_count"].eq(0),
        ["bhk", "bhk_count", "property_type"]
    ].head(30)
)

              bhk  bhk_count property_type
6882  0 BHK Villa          0         Villa

In [28]:
checks = {
    "price <= 0": df_clean["price"].le(0),
    "area <= 0": df_clean["area"].le(0),
    "carpetarea <= 0": df_clean["carpetarea"].le(0),
    "pricepersquare <= 0": df_clean["pricepersquare"].le(0),
}

for label, mask in checks.items():
    print(f"{label}: {int(mask.fillna(False).sum())} records")

price <= 0: 0 records
area <= 0: 0 records
carpetarea <= 0: 0 records
pricepersquare <= 0: 0 records

3.3 Remove Repeated Header Rows

In [29]:
# Record the number of rows before cleaning
rows_before = len(df_clean)

# Remove the 22 confirmed repeated-header records
df_clean = df_clean.loc[~combined_suspect_mask].copy()

# Reset the index after removing records
df_clean.reset_index(drop=True, inplace=True)

rows_removed = rows_before - len(df_clean)

print("Rows before:", rows_before)
print("Rows removed:", rows_removed)
print("Rows remaining:", len(df_clean))
print("Repeated header rows remaining:",
      int(
          df_clean["neworold"]
          .astype("string")
          .str.strip()
          .str.casefold()
          .eq("neworold")
          .sum()
      ))

Rows before: 37539
Rows removed: 22
Rows remaining: 37517
Repeated header rows remaining: 0

In [30]:
columns_to_inspect = [
    "bathroom",
    "balconies",
    "opensides",
    "totalfloor",
    "floor",
    "age",
    "roadfaceing",
    "facing",
    "ownership",
    "neworold",
    "status",
    "possesiondate",
]

for column in columns_to_inspect:
    print(f"\n{'=' * 50}")
    print(f"Column: {column}")
    print("Unique values:", df_clean[column].nunique(dropna=True))
    display(df_clean[column].value_counts(dropna=False).head(20))

==================================================
Column: bathroom
Unique values: 9

bathroom
2       13705
3        9880
1        5142
4        4388
<NA>     2872
5        1294
6         187
7          43
8           4
9           2
Name: count, dtype: int64[pyarrow]

==================================================
Column: balconies
Unique values: 8

balconies
<NA>    15628
1        9482
2        9480
3        2548
4         342
5          25
6          10
8           1
7           1
Name: count, dtype: int64[pyarrow]

==================================================
Column: opensides
Unique values: 4

opensides
<NA>    25934
1        4199
2        3463
4        2791
3        1130
Name: count, dtype: int64[pyarrow]

==================================================
Column: totalfloor
Unique values: 34

totalfloor
<NA>    13425
12       5482
11       3053
7        1864
10       1831
6        1507
4        1461
9        1348
8        1280
5        1112
3         724
15        576
2         570
13        539
22        402
14        370
23        302
21        277
1         276
16        175
Name: count, dtype: int64[pyarrow]

==================================================
Column: floor
Unique values: 54

floor
<NA>    5620
3,      2921
4,      2787
2,      2761
Gr      2708
5,      2691
7,      2569
1,      2329
6,      2111
8,      1454
9,      1061
3       1042
2       1008
4        963
10,      821
1        807
5        682
6        566
11,      519
7        389
Name: count, dtype: int64[pyarrow]

==================================================
Column: age
Unique values: 68

age
<NA>             9902
6 - 7 years      3552
11 - 12 years    3291
0 - 1 year       2824
5 - 6 years      2660
2 - 3 years      2558
10 - 11 years    2445
1 - 2 years      2011
3 - 4 years      1647
4 - 5 years      1018
7 - 8 years       702
8 - 9 years       548
9 - 10 years      435
5 years           390
10 years          368
16 - 17 years     366
6 years           334
1 year            285
2 years           248
15 - 16 years     192
Name: count, dtype: int64[pyarrow]

==================================================
Column: roadfaceing
Unique values: 83

roadfaceing
<NA>        30664
20 feet      1054
40 feet       826
50 feet       814
30 feet       796
100 feet      654
60 feet       450
25 feet       350
80 feet       315
200 feet      249
15 feet       201
10 feet       187
90 feet       148
35 feet        97
45 feet        73
18 feet        73
120 feet       69
150 feet       44
328 feet       39
65 feet        37
Name: count, dtype: int64[pyarrow]

==================================================
Column: facing
Unique values: 8

facing
East         20783
<NA>          6620
North         3586
West          3565
NorthEast     1932
South          526
NorthWest      289
SouthEast      126
SouthWest       90
Name: count, dtype: int64[pyarrow]

==================================================
Column: ownership
Unique values: 4

ownership
Freehold                25366
<NA>                     9383
Co-Operative Society     2616
Leasehol                  105
Power of Attorney          47
Name: count, dtype: int64[pyarrow]

==================================================
Column: neworold
Unique values: 2

neworold
Resale    25860
New       11656
<NA>          1
Name: count, dtype: int64[pyarrow]

==================================================
Column: status
Unique values: 11

status
Ready to move,Unfurnished            16641
Under Construction                    5287
Ready to move                         4927
Ready to move,Semi-Furnished          4636
Ready to move,Furnished               3571
<NA>                                  1461
Unfurnished                            446
Under Construction,Unfurnished         406
Under Construction,Semi-Furnished       75
Furnished                               41
Semi-Furnished                          21
Under Construction,Furnished             5
Name: count, dtype: int64[pyarrow]

==================================================
Column: possesiondate
Unique values: 51

possesiondate
<NA>          32803
01-12-2018     1445
01-12-2019      727
01-12-2020      464
01-03-2018      317
01-06-2018      315
01-06-2019      214
01-08-2018      113
01-03-2019      112
01-09-2018      102
01-09-2019       85
01-04-2018       82
01-07-2018       58
01-05-2019       57
01-09-2021       54
01-05-2018       48
01-02-2018       48
01-03-2020       43
01-12-2021       41
01-10-2018       36
Name: count, dtype: int64[pyarrow]

In [31]:
numeric_columns = [
    "price",
    "pricepersquare",
    "area",
    "carpetarea",
]

display(
    pd.DataFrame({
        "missing_count": df_clean[numeric_columns].isna().sum(),
        "missing_percentage": (
            df_clean[numeric_columns].isna().mean() * 100
        ).round(2),
        "data_type": df_clean[numeric_columns].dtypes.astype(str),
    })
)

                missing_count  missing_percentage data_type
price                       1                0.00     Int64
pricepersquare              1                0.00     Int64
area                       21                0.06     Int64
carpetarea              28917               77.08     Int64

### 3.4 Convert Count Columns to Numeric

Convert property count and floor-count columns into nullable integers. Nullable integers allow missing values to remain missing instead of forcing them to become zero.

In [32]:
integer_columns = [
    "bathroom",
    "balconies",
    "opensides",
    "totalfloor"
]

for column in integer_columns:
    df_clean[column] = pd.to_numeric(
        df_clean[column],
        errors="coerce"
    ).astype("Int64")

df_clean[integer_columns].info()

display(df_clean[integer_columns].describe())

<class 'pandas.DataFrame'>
RangeIndex: 37517 entries, 0 to 37516
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bathroom    34645 non-null  Int64
 1   balconies   21889 non-null  Int64
 2   opensides   11583 non-null  Int64
 3   totalfloor  24092 non-null  Int64
dtypes: Int64(4)
memory usage: 1.3 MB

       bathroom  balconies  opensides  totalfloor
count 34,645.00  21,889.00  11,583.00   24,092.00
mean       2.53       1.72       2.22       10.14
std        1.06       0.74       1.17        5.06
min        1.00       1.00       1.00        1.00
25%        2.00       1.00       1.00        7.00
50%        2.00       2.00       2.00       11.00
75%        3.00       2.00       3.00       12.00
max        9.00       8.00       4.00       35.00

In [33]:
print("Most common floor values:")
display(df_clean["floor"].value_counts(dropna=False).head(30))

print("Values containing commas:")
display(
    df_clean.loc[
        df_clean["floor"].astype("string").str.contains(
            ",", na=False
        ),
        ["floor"]
    ].drop_duplicates().head(20)
)

Most common floor values:

floor
<NA>    5620
3,      2921
4,      2787
2,      2761
Gr      2708
5,      2691
7,      2569
1,      2329
6,      2111
8,      1454
9,      1061
3       1042
2       1008
4        963
10,      821
1        807
5        682
6        566
11,      519
7        389
12,      367
9        236
8        217
10       194
14,       90
13,       87
11        86
18,       70
12        62
15,       58
Name: count, dtype: int64[pyarrow]

Values containing commas:

     floor
0       3,
4       6,
5       2,
8       4,
9       1,
13     12,
15     14,
53      7,
55     10,
59      8,
67      9,
69     11,
70      5,
81     16,
82     18,
208    20,
536    13,
749    21,
1004   22,
1066   24,

### 3.5 Standardize Floor Information

The floor column contains inconsistent formatting, including trailing commas and the abbreviation "Gr". A separate numeric feature, `floor_number`, is created to standardize floor values while preserving the original column for reference. "Gr" is interpreted as ground floor (0).

In [34]:
# Normalize text formatting
floor_text = (
    df_clean["floor"]
    .astype("string")
    .str.strip()
)

# Remove trailing commas and surrounding spaces
floor_text = floor_text.str.replace(
    r",+$", "", regex=True
).str.strip()

# Create a separate numeric feature
df_clean["floor_number"] = pd.to_numeric(
    floor_text,
    errors="coerce"
).astype("Int64")

# Interpret "Gr" as ground floor (0)
ground_mask = floor_text.str.casefold().eq("gr").fillna(False)
df_clean.loc[ground_mask, "floor_number"] = 0

# Validate the conversion
print("Original floor column:")
display(df_clean["floor"].value_counts(dropna=False).head(15))

print("\nNew floor_number column:")
display(df_clean["floor_number"].value_counts(dropna=False).sort_index())

print("\nFloor values that could not be converted:")
unconverted_mask = (
    floor_text.notna()
    & df_clean["floor_number"].isna()
)
display(
    df_clean.loc[unconverted_mask, ["floor"]]
    .drop_duplicates()
)

Original floor column:

floor
<NA>    5620
3,      2921
4,      2787
2,      2761
Gr      2708
5,      2691
7,      2569
1,      2329
6,      2111
8,      1454
9,      1061
3       1042
2       1008
4        963
10,      821
Name: count, dtype: int64[pyarrow]

New floor_number column:

floor_number
0       2708
1       3136
2       3769
3       3963
4       3750
5       3373
6       2677
7       2958
8       1671
9       1297
10      1015
11       605
12       429
13       102
14       100
15        72
16        43
17        34
18        75
19        30
20        23
21        19
22        17
23         8
24         3
25         4
26         1
27         2
30         3
31         3
32         2
34         5
<NA>    5620
Name: count, dtype: Int64

Floor values that could not be converted:

Empty DataFrame
Columns: [floor]
Index: []

In [35]:
invalid_floor_mask = (
    df_clean["floor_number"].notna()
    & df_clean["totalfloor"].notna()
    & (df_clean["floor_number"] > df_clean["totalfloor"])
)

print("Rows where floor exceeds total floors:",
      int(invalid_floor_mask.sum()))

display(
    df_clean.loc[
        invalid_floor_mask,
        ["floor", "floor_number", "totalfloor", "locality"]
    ].head(20)
)

Rows where floor exceeds total floors: 0

Empty DataFrame
Columns: [floor, floor_number, totalfloor, locality]
Index: []

### 3.6 Extract Road Width

The road-facing width column contains measurements stored as text, such as "20 feet". A separate numeric feature, `road_width_feet`, is created to support quantitative analysis. Missing values are preserved.

In [36]:
# Keep the original roadfaceing column unchanged
road_text = (
    df_clean["roadfaceing"]
    .astype("string")
    .str.strip()
)

# Extract the numeric part of the measurement
df_clean["road_width_feet"] = pd.to_numeric(
    road_text.str.extract(
        r"(\d+(?:\.\d+)?)",
        expand=False
    ),
    errors="coerce"
).astype("Float64")

# Inspect the result
print("Original road-facing values:")
display(df_clean["roadfaceing"].value_counts().head(15))

print("\nCleaned road width summary:")
display(df_clean["road_width_feet"].describe())

print("\nUnique numeric road widths:")
display(
    df_clean["road_width_feet"]
    .value_counts()
    .sort_index()
    .head(30)
)

print(
    "\nMissing road widths:",
    int(df_clean["road_width_feet"].isna().sum())
)

Original road-facing values:

roadfaceing
20 feet     1054
40 feet      826
50 feet      814
30 feet      796
100 feet     654
60 feet      450
25 feet      350
80 feet      315
200 feet     249
15 feet      201
10 feet      187
90 feet      148
35 feet       97
45 feet       73
18 feet       73
Name: count, dtype: int64[pyarrow]

Cleaned road width summary:

count   6,853.00
mean       56.97
std        97.39
min         1.00
25%        25.00
50%        40.00
75%        60.00
max     6,561.00
Name: road_width_feet, dtype: Float64

Unique numeric road widths:

road_width_feet
1.00        6
2.00        1
5.00        1
6.00       13
7.00        7
8.00        7
9.00        5
10.00     187
11.00       1
12.00      23
13.00       3
14.00      27
15.00     201
16.00      23
17.00       2
18.00      73
19.00      10
20.00    1054
22.00       7
23.00       1
24.00       7
25.00     350
26.00       2
27.00       3
29.00      25
30.00     796
32.00      22
34.00       2
35.00      97
36.00       9
Name: count, dtype: Int64

Missing road widths: 30664

### 3.7 Extract Property Age

The age column contains ranges and single-year descriptions. A numeric feature, `property_age_years`, is created using the midpoint for ranges and the stated value for single-year entries. The original age column is retained.

In [37]:
age_text = (
    df_clean["age"]
    .astype("string")
    .str.strip()
    .str.casefold()
)

# Extract the first and second numbers
age_numbers = age_text.str.extract(
    r"(\d+(?:\.\d+)?)\s*(?:-\s*(\d+(?:\.\d+)?))?",
    expand=True
)

age_start = pd.to_numeric(age_numbers[0], errors="coerce")
age_end = pd.to_numeric(age_numbers[1], errors="coerce")

# Use the midpoint for ranges; use the stated value otherwise
df_clean["property_age_years"] = (
    age_start + age_end.fillna(age_start)
) / 2

df_clean["property_age_years"] = (
    df_clean["property_age_years"].astype("Float64")
)

print("Original age examples:")
display(df_clean["age"].dropna().drop_duplicates().head(20))

print("\nConverted property age:")
display(
    df_clean[["age", "property_age_years"]]
    .drop_duplicates()
    .head(30)
)

print("\nProperty age summary:")
display(df_clean["property_age_years"].describe())

Original age examples:

0        2 - 3 years
1         0 - 1 year
6        1 - 2 years
21       6 - 7 years
26           2 years
29       3 - 4 years
30     10 - 11 years
31       7 - 8 years
33       4 - 5 years
37       5 - 6 years
41     12 - 13 years
42     11 - 12 years
47            1 year
60          17 years
61           6 years
64          12 years
74           7 years
88          20 years
114    20 - 21 years
117     9 - 10 years
Name: age, dtype: string

Converted property age:

               age  property_age_years
0      2 - 3 years                2.50
1       0 - 1 year                0.50
6      1 - 2 years                1.50
10            <NA>                <NA>
21     6 - 7 years                6.50
26         2 years                2.00
29     3 - 4 years                3.50
30   10 - 11 years               10.50
31     7 - 8 years                7.50
33     4 - 5 years                4.50
37     5 - 6 years                5.50
41   12 - 13 years               12.50
42   11 - 12 years               11.50
47          1 year                1.00
60        17 years               17.00
61         6 years                6.00
64        12 years               12.00
74         7 years                7.00
88        20 years               20.00
114  20 - 21 years               20.50
117   9 - 10 years                9.50
120  13 - 14 years               13.50
133  19 - 20 years               19.50
144  14 - 15 years               14.50
168       15 years               15.00
172  17 - 18 years               17.50
177    8 - 9 years                8.50
221       19 years               19.00
257       25 years               25.00
273       30 years               30.00

Property age summary:

count   27,615.00
mean         6.37
std          4.49
min          0.50
25%          2.50
50%          5.50
75%         10.50
max         42.00
Name: property_age_years, dtype: Float64

In [38]:
df_clean["possession_date"] = pd.to_datetime(
    df_clean["possesiondate"],
    format="%d-%m-%Y",
    errors="coerce"
)

print("Possession date data type:",
      df_clean["possession_date"].dtype)

print("Missing possession dates:",
      int(df_clean["possession_date"].isna().sum()))

print("\nEarliest possession date:",
      df_clean["possession_date"].min())

print("Latest possession date:",
      df_clean["possession_date"].max())

display(
    df_clean[["possesiondate", "possession_date"]]
    .dropna()
    .head(10)
)

Possession date data type: datetime64[us]
Missing possession dates: 32803

Earliest possession date: 2018-01-01 00:00:00
Latest possession date: 2025-12-01 00:00:00

   possesiondate possession_date
10    01-11-2019      2019-11-01
11    01-11-2019      2019-11-01
13    01-03-2018      2018-03-01
15    01-12-2018      2018-12-01
53    01-12-2019      2019-12-01
56    01-07-2019      2019-07-01
57    01-12-2020      2020-12-01
58    01-12-2020      2020-12-01
59    01-11-2019      2019-11-01
68    01-12-2020      2020-12-01

3.8 Investigate Extreme Values

In [39]:
# Inspect the 15 largest extracted road widths
largest_roads = df_clean.nlargest(
    15, "road_width_feet"
)

display(
    largest_roads[
        [
            "roadfaceing",
            "road_width_feet",
            "locality",
            "projectname",
            "area",
            "price"
        ]
    ]
)

,roadfaceing,road_width_feet,locality,projectname,area,price
36362,6561 feet,"6,561.00",Wagholi,Kolte Patil IVY Apartments,1585,7000000
28506,1000 feet,"1,000.00",Rahatani,GK Royale Rahadki Greens,617,4300000
33920,1000 feet,"1,000.00",Manjari,Gemini Grand Bay,1150,6500000
24344,984 feet,984.00,Hadapsar,Loharuka Green City,860,5500000
27628,984 feet,984.00,Hadapsar,Loharuka Green City,860,5500000
28560,984 feet,984.00,Pimple Saudagar,GK Rose Icon,650,5000000
30033,780 feet,780.00,Hadapsar,Dreams Elina,780,4000000
8129,656 feet,656.00,Wagholi,Marvel Ganga Fria 2,1255,6600000
29494,656 feet,656.00,Hadapsar,Dreams Onella,1100,5500000
30353,656 feet,656.00,Pimple Saudagar,GK Rose Icon,570,4600000
29767,500 feet,500.00,Kothrud,Pethkar Society,865,10000000
36607,492 feet,492.00,Vishrantwadi,<NA>,800,3200000
4657,400 feet,400.00,Kalyani Nagar,Atul Leela Garden,1290,12000000
5965,400 feet,400.00,Kharadi,Geras Emerald City,1600,7700000
7625,400 feet,400.00,Kalyani Nagar,BramhaCorp Bramha Sun City Phase 2,1050,8200000

In [40]:
oldest_properties = df_clean.nlargest(
    15, "property_age_years"
)

display(
    oldest_properties[
        [
            "age",
            "property_age_years",
            "locality",
            "projectname",
            "bhk",
            "price"
        ]
    ]
)

,age,property_age_years,locality,projectname,bhk,price
26549,42 years,42.00,Bund Garden,<NA>,2 BHK Apartment,8000000
19221,41 - 42 years,41.50,Bund Garden,<NA>,2 BHK Apartment,13400000
21867,41 - 42 years,41.50,Bund Garden,<NA>,2 BHK Apartment,8000000
11829,40 years,40.00,Rasta Peth,<NA>,2 BHK Apartment,8000000
16083,37 - 38 years,37.50,Prabhat Road,<NA>,2 BHK Apartment,12500000
17341,35 - 36 years,35.50,Model Colony,<NA>,2 BHK Apartment,13500000
35347,35 - 36 years,35.50,Gultekdi,Meera Meera Housing Society,1 BHK Apartment,5800000
18408,35 years,35.00,Model Colony,<NA>,1 BHK Independent House,16000000
29965,33 - 34 years,33.50,Prabhat Road,Builder not to say,3 BHK Apartment,14000000
33815,32 - 33 years,32.50,Mukund Nagar,<NA>,3 BHK Apartment,14500000
24262,31 - 32 years,31.50,Yerawada,Builder Sunehri Nivas,3 BHK Independent House,3500000
27579,31 - 32 years,31.50,Yerawada,Builder Sunehri Nivas,3 BHK Independent House,3500000
789,30 - 31 years,30.50,Fatima Nagar,<NA>,4 BHK Apartment,8000000
2642,30 - 31 years,30.50,Fatima Nagar,<NA>,4 BHK Apartment,8000000
18064,30 - 31 years,30.50,Chinchwad Station Road,<NA>,1 BHK Apartment,3600000

In [41]:
print("Ownership values before correction:")
display(df_clean["ownership"].value_counts(dropna=False))

df_clean["ownership"] = df_clean["ownership"].replace({
    "Leasehol": "Leasehold"
})

print("\nOwnership values after correction:")
display(df_clean["ownership"].value_counts(dropna=False))

Ownership values before correction:

ownership
Freehold                25366
<NA>                     9383
Co-Operative Society     2616
Leasehol                  105
Power of Attorney          47
Name: count, dtype: int64[pyarrow]

Ownership values after correction:

ownership
Freehold                25366
<NA>                     9383
Co-Operative Society     2616
Leasehold                 105
Power of Attorney          47
Name: count, dtype: int64[pyarrow]

In [42]:
numeric_columns = [
    "price",
    "pricepersquare",
    "area",
    "carpetarea",
    "bhk_count",
    "bathroom",
    "balconies",
    "totalfloor",
    "floor_number",
    "road_width_feet",
    "property_age_years"
]

numeric_summary = pd.DataFrame({
    "data_type": df_clean[numeric_columns].dtypes.astype(str),
    "missing_count": df_clean[numeric_columns].isna().sum(),
    "missing_percentage": (
        df_clean[numeric_columns].isna().mean() * 100
    ).round(2),
    "unique_values": df_clean[numeric_columns].nunique()
})

display(numeric_summary)

                   data_type  missing_count  missing_percentage  unique_values
price                  Int64              1                0.00           3341
pricepersquare         Int64              1                0.00           7085
area                   Int64             21                0.06           2379
carpetarea             Int64          28917               77.08           1231
bhk_count              Int64           1248                3.33              9
bathroom               Int64           2872                7.66              9
balconies              Int64          15628               41.66              8
totalfloor             Int64          13425               35.78             34
floor_number           Int64           5620               14.98             32
road_width_feet      Float64          30664               81.73             83
property_age_years   Float64           9902               26.39             68

In [43]:
print("Dataset shape:", df_clean.shape)
print("Duplicate rows:", df_clean.duplicated().sum())
print("Missing prices:", df_clean["price"].isna().sum())
print("Non-positive prices:",
      int((df_clean["price"].dropna() <= 0).sum()))

print("\nPrice distribution:")
display(df_clean["price"].describe())

Dataset shape: (37517, 29)
Duplicate rows: 7836
Missing prices: 1
Non-positive prices: 0

Price distribution:

count        37,516.00
mean     14,745,248.32
std      17,104,214.67
min         100,000.00
25%       5,600,000.00
50%       8,589,950.00
75%      16,000,000.00
max     269,000,000.00
Name: price, dtype: Float64

In [44]:
# Identify all rows that have an exact duplicate
duplicate_mask = df_clean.duplicated(keep=False)

print("Rows participating in duplicate groups:",
      int(duplicate_mask.sum()))

print("Extra duplicate rows beyond the first occurrence:",
      int(df_clean.duplicated().sum()))

# Inspect a sample using relevant property details
review_columns = [
    "locality",
    "projectname",
    "bhk",
    "area",
    "price",
    "pricepersquare",
    "floor",
    "totalfloor",
    "age",
    "status",
    "ownership"
]

display(
    df_clean.loc[duplicate_mask, review_columns]
    .head(25)
)

Rows participating in duplicate groups: 13689
Extra duplicate rows beyond the first occurrence: 7836

,locality,projectname,bhk,area,price,pricepersquare,floor,totalfloor,age,status,ownership
0,Deccan Gymkhana,Bhansali Prive Rio,3 BHK Apartment,1611,27000000,16759,"3,",6,2 - 3 years,Ready to move,Co-Operative Society
1,Kharadi,Goel Ganga Platino,2 BHK Apartment,1279,7610050,5950,1,<NA>,0 - 1 year,Ready to move,Freehold
2,Sus,Vilas Javdekar Yashwin,1 BHK Apartment,670,4100000,6119,1,<NA>,0 - 1 year,Ready to move,Freehold
3,Bavdhan,Rohan Ishan,2 BHK Apartment,956,5736000,6000,1,<NA>,2 - 3 years,Ready to move,Freehold
4,Deccan Gymkhana,Swojas Aavishkar,3 BHK Apartment,1706,29002000,17000,"6,",9,0 - 1 year,Ready to move,Freehold
5,Mundhwa,PGD Pinnacle,2 BHK Apartment,1015,4720765,4651,"2,",10,0 - 1 year,Ready to move,Freehold
6,Viman Nagar,Marvel Piazza Phase 01,4 BHK Apartment,3725,30172500,8100,1,<NA>,1 - 2 years,Ready to move,Freehold
7,Baner,Puraniks Aldea Anexo,1 BHK Apartment,450,4000000,8889,1,<NA>,0 - 1 year,Ready to move,Freehold
8,Law collage Road,Swojas Gulmohar,3 BHK Apartment,1650,24000000,14545,"4,",6,1 - 2 years,"Ready to move,Unfurnished",Freehold
9,Mahalunge,Puraniks Aldea Espanola,1 BHK Apartment,449,2783351,6199,"1,",15,0 - 1 year,Ready to move,Freehold
10,Mundhwa,Purva Silversands,1 BHK Apartment,625,3281250,5250,"1,",27,<NA>,Under Construction,Freehold
11,Mundhwa,Purva Silversands,2 BHK Apartment,900,4725000,5250,"1,",27,<NA>,Under Construction,Freehold
12,Deccan Gymkhana,Darode Matru Chhaya,2 BHK Apartment,1100,20300000,18454,"1,",5,1 - 2 years,"Ready to move,Unfurnished",<NA>
13,Bhukum,Skyi Manas Lake,4 BHK Apartment,3300,18000000,5454,"12,",12,<NA>,Under Construction,Co-Operative Society
14,Baner,Builder Orchid 10,2 BHK Apartment,1305,9000000,6896,"2,",5,0 - 1 year,Ready to move,Freehold
15,Hinjewadi,Kasturi Eon Homes,3 BHK Apartment,1500,9200000,6133,"14,",21,<NA>,Under Construction,Freehold
16,Hadapsar,<NA>,2 BHK Apartment,1050,6000000,5714,<NA>,<NA>,<NA>,Ready to move,<NA>
17,Hadapsar Gaon,Agarwal Constructions Pune Shri Krishna Complex,1 BHK Apartment,575,3200000,5565,<NA>,<NA>,<NA>,"Ready to move,Unfurnished",<NA>
18,Sasane Nagar,Subhash Builder Vardhaman Township,1 BHK Apartment,600,2700000,4500,<NA>,<NA>,<NA>,"Ready to move,Unfurnished",<NA>
19,NIBM Annex Mohammadwadi,<NA>,2 BHK Apartment,900,4300000,4777,<NA>,<NA>,<NA>,"Ready to move,Unfurnished",<NA>
20,Salunke Vihar,<NA>,1 BHK Apartment,675,3800000,5629,<NA>,<NA>,<NA>,"Ready to move,Furnished",<NA>
21,NIBM,<NA>,2 BHK Apartment,1100,5800000,5272,<NA>,<NA>,6 - 7 years,"Ready to move,Unfurnished",<NA>
22,NIBM,<NA>,2 BHK Apartment,1050,5800000,5523,<NA>,<NA>,<NA>,"Ready to move,Unfurnished",<NA>
23,Hadapsar,Builder amar shrusti,Residential Plot,2857,12400000,4340,<NA>,<NA>,<NA>,Unfurnished,<NA>
24,Hadapsar,Builder amar shrusti,Residential Plot,7700,23100000,3000,<NA>,<NA>,<NA>,Unfurnished,<NA>

In [45]:
missing_price_mask = df_clean["price"].isna()

display(
    df_clean.loc[
        missing_price_mask,
        review_columns
    ]
)

,locality,projectname,bhk,area,price,pricepersquare,floor,totalfloor,age,status,ownership
28661,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [46]:
print(
    "Rows with missing price:",
    int(df_clean["price"].isna().sum())
)

print(
    "Rows with missing price per square foot:",
    int(df_clean["pricepersquare"].isna().sum())
)

display(
    df_clean.loc[
        df_clean["price"].isna()
        | df_clean["pricepersquare"].isna(),
        ["locality", "area", "price", "pricepersquare"]
    ]
)

Rows with missing price: 1
Rows with missing price per square foot: 1

      locality  area  price  pricepersquare
28661     <NA>  <NA>   <NA>            <NA>

In [47]:
df_clean["ownership"] = df_clean["ownership"].replace({
    "Leasehol": "Leasehold"
})

display(df_clean["ownership"].value_counts(dropna=False))

ownership
Freehold                25366
<NA>                     9383
Co-Operative Society     2616
Leasehold                 105
Power of Attorney          47
Name: count, dtype: int64[pyarrow]

In [48]:
# Check whether every column in this row is missing
row = df_clean.loc[28661]

print("Total columns:", len(df_clean.columns))
print("Missing values in row:", int(row.isna().sum()))
print("Entire row is missing:", bool(row.isna().all()))

Total columns: 29
Missing values in row: 29
Entire row is missing: True

In [49]:
# Record the dataset size before final row cleaning
rows_before = len(df_clean)

# Remove completely empty records
empty_row_mask = df_clean.isna().all(axis=1)
empty_rows_removed = int(empty_row_mask.sum())

df_clean = df_clean.loc[~empty_row_mask].copy()

# Count and remove exact duplicate rows
duplicates_before = int(df_clean.duplicated().sum())

df_clean = df_clean.drop_duplicates().reset_index(drop=True)

# Report the changes
print("Rows before cleaning:", rows_before)
print("Completely empty rows removed:", empty_rows_removed)
print("Exact duplicate rows removed:", duplicates_before)
print("Rows after cleaning:", len(df_clean))
print("Remaining duplicate rows:", int(df_clean.duplicated().sum()))

Rows before cleaning: 37517
Completely empty rows removed: 1
Exact duplicate rows removed: 7836
Rows after cleaning: 29680
Remaining duplicate rows: 0

In [50]:
print("Final dataset shape:", df_clean.shape)
print("\nMissing values in important columns:")

important_columns = [
    "price",
    "area",
    "bhk_count",
    "bathroom",
    "floor_number",
    "property_age_years"
]

display(
    pd.DataFrame({
        "missing_count": df_clean[important_columns].isna().sum(),
        "missing_percentage": (
            df_clean[important_columns].isna().mean() * 100
        ).round(2)
    })
)

print("\nRemaining fully empty rows:",
      int(df_clean.isna().all(axis=1).sum()))

print("Remaining exact duplicates:",
      int(df_clean.duplicated().sum()))

print("Non-positive prices:",
      int((df_clean["price"].dropna() <= 0).sum()))

Final dataset shape: (29680, 29)

Missing values in important columns:

                    missing_count  missing_percentage
price                           0                0.00
area                           13                0.04
bhk_count                     645                2.17
bathroom                     1854                6.25
floor_number                 3979               13.41
property_age_years           7212               24.30

Remaining fully empty rows: 0
Remaining exact duplicates: 0
Non-positive prices: 0

In [51]:

# Create the processed-data folder if it doesn't exist
processed_dir = project_root / "data" / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

# Define the output file path
output_file = processed_dir / "pune_property_cleaned.csv"

# Save the cleaned dataset
df_clean.to_csv(output_file, index=False)

# Verify that the file was saved successfully
print("Dataset saved successfully!")
print("File location:", output_file)
print("File exists:", output_file.exists())
print("Final shape:", df_clean.shape)

Dataset saved successfully!
File location: d:\Pune-House-Price-Prediction\data\processed\pune_property_cleaned.csv
File exists: True
Final shape: (29680, 29)

## Data Cleaning Summary

The original dataset contained 37,539 rows and 24 columns.

The following cleaning and preprocessing steps were performed:

1. Removed the unnecessary sequential index column.
2. Trimmed whitespace and standardized common missing-value markers.
3. Identified and removed 22 repeated header rows.
4. Converted price, area, carpet area, and price per square unit into numeric formats.
5. Created `bhk_count` and `property_type` from the original BHK field.
6. Created numeric features for floor number, road width, and property age.
7. Converted the possession date into a datetime format.
8. Standardized the ownership value `Leasehol` to `Leasehold`.
9. Removed one completely empty row.
10. Removed 7,836 exact duplicate rows.

**Final dataset:** 29,680 rows and 29 columns.

**Final validation:** No fully empty rows, no exact duplicate rows, no missing prices, and no non-positive prices remain.

Missing values in other features were retained for further investigation and appropriate handling during model preprocessing.

Potential anomalies, including unusually large road-width values and the `0 BHK Villa` record, should be reviewed before final model training.